# Generated by Django 3.2.16 on 2022-11-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('birthDate', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('updateOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
